apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttrend
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  ttrend
  template:
    metadata:
      labels:
        app:  ttrend
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - name:  devops
        image: devops005.jfrog.io/artifactory/devops-docker-local/ttrend:2.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: CONSUMER_KEY
          value: "G6lmKhsi0V9TvXt6oKTfjRBCr"
        - name: CONSUMER_SECRET
          value: "bEyDk8X0p8SQd4376eoNV4nH8To22sHcJOoFt0ZqOKS37hhI4q"
        - name: ACCESS_TOKEN
          value: "9703354-52rXHD6EeOQeYyhtNz1w8UVOgbcLcgOo4O7MB6WV3"
        - name: ACCESS_TOKEN_SECRET
          value: "zBThlZDEp8qnu7NwwdHNth8eg3Rf9zqbvUEFUTaZtN2SF"